name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger this workflow when changes are pushed to the 'main' branch

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # You can set the Python version you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install
